### ISSUE TITLE
change execution order to make merge_bam_files run sooner

### ISSUE THREAD

**Issue by diljotgrewal** [mondrian-scwgs/mondrian#22]

**Comment by diljotgrewal** [comment]
updating alignment: for contamination i need num reads. 

in the old version, it came from collectwgsmetrics (which double counts when there’s secondary alignments). switched it to a simpler read counting with no double counting. 

this might add small variance and wont match dlp

**Comment by diljotgrewal** [comment]
https://github.com/mondrian-scwgs/mondrian/commit/e26eacac612cb2ff5be6b8392e93046e2427c9f0#diff-29b4b7185d472e2b18d12f08ba229bb332668389b7c1c8b8bd4ff51f3db3a8ca

-  updated the contamination task to take in fastqscreen summary metrics as input
- added total reads to fastqscreen summary metrics
- updated merge_bam_files to take contamination task as input

**Comment by JenniferShelton** [comment]
Thanks @diljotgrewal , 
At first glance I thought the merge may have been held until the scatter completes (the way that cromwell has handled subworkflows). I see the input dependency that was causing the merge to wait for the QC steps. This should help us speed the runs up
